# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /vanakam_da_mapula

# Copy the current directory contents into the container at /app
COPY app.py /vanakam_da_mapula

# Install Flask
RUN pip install flask

# Expose port 5000 for Flask
EXPOSE 5000

# Define the command to run the application
CMD ["python", "app.py"]
