apiVersion: v1
kind: Pod
metadata:
  name: hostpath-example-1
spec:
  containers:
  - name: hostpath-container-1
    image: nginx
    ports:
    - containerPort: 80 # Specify the container's port
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: shared-volume
  volumes:
  - name: shared-volume
    hostPath:
      path: /vijay/html
      type: Directory
